apiVersion: v1
kind: Service
metadata:
  name: bouwmeester-backend
  namespace: bouwmeester
  labels:
    app.kubernetes.io/name: bouwmeester-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bouwmeester
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bouwmeester-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
