apiVersion: v1
kind: ConfigMap
metadata:
  name: bouwmeester-config
  namespace: bouwmeester
  labels:
    app.kubernetes.io/part-of: bouwmeester
data:
  APP_NAME: "Bouwmeester"
  DEBUG: "false"
  OIDC_ISSUER: "https://login.rijkscloud.nl/realms/bouwmeester"
  OIDC_CLIENT_ID: "bouwmeester"
