apiVersion: v1
kind: Service
metadata:
  name: bouwmeester-frontend
  namespace: bouwmeester
  labels:
    app.kubernetes.io/name: bouwmeester-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: bouwmeester
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bouwmeester-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
